export class QueryReturn {
    ReturnNumber:number;
    OrderNumber:string;
    ProductCode:string;
    ProductName:string;
    CustomerCode:string;
    CustomerName:string;
    StateId:number;
    StateName:string;
    PackageNumber:number;
    ModificationDate:Date;
    LogisticsReturnDate:Date;
    LogisticsReturnUser:string;
    LogisticsReturnObs:string;
    ProductionConfirmationDate:Date;
    ProductionConfirmationUser:string;
    ProductionConfirmationObs:string;
    ProductionReturnDate:Date;
    ProductionReturnUser:string;
    ProductionReturnObs:string;
    LogisticsConfirmationDate:Date;
    LogisticsConfirmationUser:string;
    LogisticsConfirmationObs:string;
}
